name: Teste TypeScript

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Installar dependências
      run: npm install

    - name: Compilar TypeScript
      run: npm run build

    - name: Executar script TypeScript
      run: node dist/test.js
